name: "Deploy 'P3D Legacy Server'"

on:
  repository_dispatch:
    types:
      - deploy-docker-image
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy 'P3D Legacy Server'"
    runs-on: ubuntu-latest
    environment:
      name: 'p3d-backend'
      url: 'https://karp.pokemon3d.net'
    steps:

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u=P3D-Legacy -p=${{ secrets.TOKEN_GPR }} ghcr.io
            docker image pull ghcr.io/p3d-legacy/p3d-legacy-server:latest;
            docker stack deploy --prune --resolve-image always -c /deploy/p3d-legacy-server/docker-compose.yml p3dlegacyserver;

      - name: Checkout Repository
        if: always()
        uses: actions/checkout@v4

      - name: Notify
        if: always()
        env:
          BUILD_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: bash ./.github/workflows/discord.sh
