name: "Deploy P3D Legacy Server Next"

on:
  repository_dispatch:
    types:
      - deploy-docker-image
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy P3D Legacy Server Next"
    runs-on: ubuntu-latest
    environment:
      name: 'next-p3d-backend'
      url: 'https://karp.pokemon3d.net'
    steps:
    
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker login -u=P3D-Legacy -p=${{ secrets.TOKEN_GPR }} ghcr.io
          docker image pull ghcr.io/p3d-legacy/p3d-legacy-server:latest;
          docker stack deploy --prune --resolve-image always --with-registry-auth -c /deploy/next-p3d-legacy-server/docker-compose.yml nextp3dlegacyserver;

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Notify
      if: always()
      env:
        BUILD_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
      run: curl -s https://raw.githubusercontent.com/nebularg/actions-discord-webhook/95e7fbbd5c40116edd9ccee7a5703618ee30e3b6/send.sh | bash
