name: Publish Docker Image on Commit

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker-publish-qa.yml'
      - 'src/**'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
  workflow_dispatch:

jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: P3D-Legacy
        password: ${{ secrets.TOKEN_GPR }}

    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./src/P3D.Legacy.Server/Dockerfile
        push: true
        tags: ghcr.io/p3d-legacy/p3d-legacy-server:latest-qa

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Trigger Deploy
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.TOKEN_GPR }}
        repository: P3D-Legacy/P3D-Legacy-Server
        event-type: deploy-docker-image-qa
